### PR TITLE
Allow enabling layers at Device level

### PR DESCRIPTION
**Pull request by discosultan**
Fixes https://github.com/discosultan/VulkanCore/issues/25

### CODE REVIEW

**Comment by WardBenjamin** [comment]
Looks good to me on paper; I haven't had a chance to test.

**Comment by amerkoleci** [comment]
ppEnabledLayerNames is deprecated and ignored.
So this one doesn't make sense tho.

https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkDeviceCreateInfo.html

**Comment by discosultan** [comment]
The only reason for the change is to make it possible to define those layers in case someone is targeting a very early version of Vulkan runtime. Note that it's documented as deprecated and also not exposed in the constructor signature.

**Comment by amerkoleci** [comment]
I see, maybe marking the EnabledLayerCount and EnabledLayerNames with Deprecated attribute would help that approach.

**Comment by WardBenjamin** [comment]
Not a bad idea - the field should be marked with an `[Obsolete("Reason")]` attribute.

**Pull request merged**
