### PR TITLE
IEquatable and various improvements

### PR DESCRIPTION
**Pull request by amerkoleci**
- Size renamed in PointerSize for better naming conventions (IE: avoid confusions with System.Drawing.Size).
- Implemented various IEquatable to Rect2D, Rect3D, Offset2D, Offset3D and lot of more.
- Code separation.
- GetHashCode implementation.

### CODE REVIEW

**Comment by amerkoleci** [comment]
Maybe  DeviceSize as Vulkan wouldn't be bad.

**Comment by discosultan** [comment]
`DeviceSize` is actually a typedef to `Int64` so they are different types.

**Comment by amerkoleci** [comment]
You can merge and revert back to Size then

**Comment by discosultan** [comment]
@amerkoleci Some more comments :)

Actually, it is a good point that `Size` conflicts with `System.Drawing.Size`. What if we removed the custom type altogether and simply used `IntPtr`? While I don't like the name of `IntPtr` for something that represents a size, it is often used as a .NET equivalent to `size_t` and is a familiar type to developers.

I very much like the `IEquatable{T}` additions!

I'm a little reluctant to separate the variants of `Rect` each into a separate file. That would mean that this should also be done for `Offset`, `Extent`, `Color` types to stay consistent and it will quickly bloat up the solution explorer/folder with a lot of relatively small files. I wouldn't want to categorize them to a sub-folder either as at the moment, a folder also represents a type's namespace.

Anyway, once again, thanks for your contributions! I'll get at least some of the stuff added today.

**Comment by amerkoleci** [comment]
Make sure that size_t in c++ is int in C# on x64 and long on x64.

**Comment by discosultan** [comment]
`IntPtr` behaves exactly like that (being 4 bytes in x86 and 8 bytes in x64).

**Comment by amerkoleci** [comment]
Okay, take what you need from the pull and I can proceed futher and do something else if you want.

**Comment by discosultan** [comment]
One big downside to using `IntPtr` instead of `Size` is the fact that `IntPtr` does not implement any implicit conversions from `Int32` or `Int64` to `IntPtr`. This makes it very annoying to pass a size in bytes because you need to always write `new IntPtr(128)`, for example.

**Comment by amerkoleci** [comment]
Closing now tho.

**Pull request closed without merging**
