### PR TITLE
Additional constructors to create structures

### PR DESCRIPTION
**Pull request by BastianBlokland**
Added a few more constructors to the structures that had none. Also i've added a few more arguments to the SwapchainCreateInfoKhr constructor, or was there a specific reason why not all variables where configurable from the constructor?

### CODE REVIEW

**Comment by discosultan** [comment]
LGTM, thanks!

> was there a specific reason why not all variables where configurable from the constructor?

Can't recall. Might have been that parameters which were not required for the most "common" use case were left out. But I like them all being settable through ctor with reasonable defaults.

**Comment by BastianBlokland** [comment]
Thanks  👍

**Comment by discosultan** [comment]
I'll release a new nuget as soon as https://github.com/discosultan/VulkanCore/issues/25 is resolved. Opening a PR for it very soon.

**Comment by WardBenjamin** [comment]
Awesome!

**Pull request merged**
