### PR TITLE
WIP: vkEnumeratePhysicalDeviceGroupsKHX support

### PR DESCRIPTION
**Pull request by TYoung86**
Load vkEnumeratePhysicalDeviceGroupsKHX from static export, but fall back to using instance.GetProc (vkGetInstanceProcAddr)

See #8

### CODE REVIEW

**Comment by TYoung86** [comment]
During binding from instance.GetProc<TDelegate>(...):
Cannot marshal 'parameter #3': Pointers cannot reference marshaled structures.  Use ByRef instead.

**Comment by TYoung86** [comment]
Now I have an AccessViolationException during after vkCreateDevice on line 26 of Device.cs ...

**Comment by TYoung86** [comment]
Nope, handles for EnumeratePhysicalDeviceGroups and EnumeratePhysicalDevices both give the error with vkCreateDevice when Next is specified on the DeviceCreateInfo.Native structure... still investigating.

**Comment by TYoung86** [comment]
DeviceGroupDeviceCreateInfoKhx as allocated on the managed stack has an incorrect structure.

Created a Native for it, created a ToNative method for the structure, but it must be exposed as public for use by anyone filling the 'Next' IntPtr on CreateDeviceInfo... suggestions?

**Comment by TYoung86** [comment]
My formatting rules are K&R with tabs, while you're Allman with spaces... I adhered to Allman for the changes, but didn't notice the spaces. I'll make a commit this afternoon to convert to spaces.

**Comment by discosultan** [comment]
For extension structs used in the `Next` chain, I haven't set specific rules on how they should be built.

In case the managed form differs from the native form (i.e. it contains an array), it might be confusing to expose both a public managed and native form and expect user to convert between them through a `ToNative` method (though, I know I did that somewhere). What I've done recently, is only expose the native form publicly and expect user to make any necessary marshalling/array pinning himself. Not sure which is the better choice.

It would be interesting to hear from a user's perspective on what would feel an intuitive way to work in such a scenario.

----

I'll try to also test the `vkEnumeratePhysicalDeviceGroupsKHX` command in upcoming days.

**Comment by TYoung86** [comment]
Would you prefer to follow a path that simply doesn't utilize ToNative / FromNative? See #10

**Comment by discosultan** [comment]
I think `ToNative` and `FromNative` are fine, actually. At least it follows the same pattern as VulkanCore does internally. So this PR is good in that respect :+1: 

I also updated my last comment on https://github.com/discosultan/VulkanCore/issues/8. The issue is quite big as only a handful of extension commands are known to be statically exported (those part of Windows System Integration)(all core commands are statically exported). I'm currently figuring out the best pattern to remedy that.

**Comment by discosultan** [comment]
@TYoung86 I incorporated the following changes directly from your PR:

- .editorconfig changes except for `line_ending` which atm is intended to be managed by VCS
- Use `Constant.MaxDeviceGroupSizeKhx` instead of magic number

I took a slightly different approach for passing `DeviceGroupDeviceCreateInfoKhx` to `Next` chain:

- [Native form](
 https://github.com/discosultan/VulkanCore/blob/08d9c813479bb080623dd1135265770c9dec0d94/Src/Khx/DeviceExtensions.cs#L889-L912)
- [Usage (not sure if I'm using it correctly)](https://github.com/discosultan/VulkanCore/blob/08d9c813479bb080623dd1135265770c9dec0d94/Tests/Issues/OverambitiousStaticCommandImportTest.cs#L47-L54)

I'm open to feedback. I also liked your class approach as it would allow automatically freeing any unmanaged memory by implementing a finalizer. On the other hand, every single data structure moving between Vulkan is currently implemented as a struct.

Anyway, thanks for contributing!

**Pull request closed without merging**
